### ISSUE TITLE
Erro ao buscar CEP que foi desmembrado

### ISSUE THREAD

**Issue by gagustavo** [mbodock/django-cepfield#10]
Os correios às vezes desmembram um CEP em mais de um. O que acaba quebrando a consulta, pois o resultado vem com mais de uma linha na tabela de resultado e o parser não tá pronto para isso.

Não sei como poderia resolver isso, talvez pegando apenas o primeiro resultado. Já que o certo seria o novo CEP ser informado pelo usuário final.

Exemplo:
O CEP `59603-190` foi desmembrado e tem dois CEPs resultantes.

<img width="676" alt="Screen Shot 2020-09-28 at 14 59 36" src="https://user-images.githubusercontent.com/4053685/94468716-44c12780-019b-11eb-9d68-fdabd960323c.png">

**Comment by gagustavo** [comment]
Possível solução é alterar o método `_separa_labels_conteudo` para considera apenas as duas primeiras linhas da tabela, pegando assim apenas o cabeçalho e o primeiro resultado.

A sugestão abaixo adiciona o `[:2]` ao trecho de código:

```python
cabecalhos, dados = tuple(
   i.getchildren() for i in self.tabela_html.getchildren()[:2]
)
```

Vou abrir um PR e façam suas avaliações.

**Comment by lramosduarte** [comment]
Não sabia que eles faziam um split, será se rola um merge também? 

Isso poderia até invalidar os ceps que ficam no cache local.

**Comment by gagustavo** [comment]
> Não sabia que eles faziam um split, será se rola um merge também?

Com certeza eles fazem qualquer coisa. Já vi CEP sendo removido. Alguns endereços possuem mais de um CEP (nome de rua e bairro). E tem CEP específico de prédios/edifícios.

Então pode esperar qualquer coisa.
