### ISSUE TITLE
Requests Dependency Incompatibility

### ISSUE THREAD

**Issue by gagustavo** [mbodock/django-cepfield#3]
Hi,
In my application the `requests` library is in a more updated version .
How to resolve this?

Thanks!

```bash
django-cepfield 0.2.0 has requirement requests==2.9.1, but you'll have requests 2.13.0 which is incompatible.
```

**Comment by mbodock** [comment]
Check if your project can run with `requests==2.9.1`. (temporarily)

But I'll update the dependency of this to use any requests version greater than 2.9.

Thanks for letting me know.
