### ISSUE TITLE
Lib não encontra novos CEPs

### ISSUE THREAD

**Issue by gagustavo** [mbodock/django-cepfield#4]
Só funciona com os CEPs que estão no cache(banco de dados). 
Acredito que as consultas ao site dos correios não estão mais funcionando.

**Comment by mbodock** [comment]
Endpoint não mudou. Nem o payload. Investigando se é algo no parser.

**Comment by lramosduarte** [comment]
A versão nova ainda está assim @gagustavo? Eu tinha feito uma PR em uma epoca que essa URL ficou indisponível, trocando até o parser.

Acho que a PR foi essa #2 .

**Comment by mbodock** [comment]
Estou tendo alguns problemas com o Python2 incompatibilidade do Django2.

Tentarei corrigir.

**Comment by mbodock** [comment]
@lramosduarte você pode fazer o release por favor?

**Comment by lramosduarte** [comment]
Claro, mas só poderei no sábado.

**Comment by mbodock** [comment]
Nova versão lançada.

@gagustavo poderia testar por favor?
