### ISSUE TITLE
Exception quando não encontra um cep

### ISSUE THREAD

**Issue by lramosduarte** [mbodock/django-cepfield#6]
### **O que esta acontecendo:**
Quando é realizado uma busca de um cep que não é encontrado o parser dispara um `IndexError`.

### **Sugestão do que deveria acontecer:**
Retornar um `exception` de Cep não encontrado, **mas isso pode gerar um problema de compatibilidade com os sistemas que utilizam a lib**.
Poderia ser retornado apenas um objeto vazio, mas dá a impressão de `bug`.

### **Imagens:**
![image](https://user-images.githubusercontent.com/8976314/71492830-03b97280-2819-11ea-942b-aa306ab097cf.png)

**Comment by lramosduarte** [comment]
Numero do cep pesquisado: **88330-000**

**Comment by mbodock** [comment]
A `ValidationError('CEP não encontrado')` deve ser retornada nesse caso.

O comportamento esperado não irá mudar, o que leva a crer que serão poucos casos de incompatibilidade (mas nunca se sabe né [1]). Afinal o CEP não foi encontrado, ele existindo ou não.

Você pode/quer resolver isso @lramosduarte ?

Atenciosamente.

1- https://xkcd.com/1172/

**Comment by lramosduarte** [comment]
Boa! Eu esqueci que isso ocorre dentro do form.

Posso realizar a correção sim, mas devo fazer no dia 30+/-
